version: "3.3"
services:
  wouxun-si-beta:
    image: registry.susa.cloud/wouxun-si:v0.0.18
    environment:
      TZ: Europe/Ljubljana
    ports:
      - 3069:3000
    networks:
      - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.wouxun-si-beta-http.middlewares: https-redirect
        traefik.http.routers.wouxun-si-beta-http.rule: Host(`beta.wouxun.si`)
        traefik.http.routers.wouxun-si-beta-https.tls.certresolver: le
        traefik.http.routers.wouxun-si-beta-https.entrypoints: https
        traefik.http.routers.wouxun-si-beta-https.rule: Host(`beta.wouxun.si`)
        traefik.http.routers.wouxun-si-beta-http.entrypoints: http
        traefik.constraint-label: traefik-public
        traefik.http.services.wouxun-si-beta.loadbalancer.server.port: "3000"
        traefik.docker.network: traefik-public
        traefik.enable: "true"
        traefik.http.routers.wouxun-si-beta-https.tls: "true"
      update_config:
        delay: 10s
        failure_action: rollback
      restart_policy:
        window: 120s
        max_attempts: 3
networks:
  traefik-public:
    external: true
